### ISSUE TITLE
markdown processing only in view

### ISSUE THREAD

**Issue by rolojf** [dillonkearns/elm-pages-3-alpha-starter#3]
Hola Dillon,

Just sharing with you my observations trying out the 3.0 alpha:

### PROBLEM:
I used to have my Data record defined as:

> type alias Data =
>     { delMD : ContenidoConDatos }
> 
> type alias ContenidoConDatos =
>      { body : List (Html Msg), title : String }

Then I used to parse and render the markdown in the data funcion.

Now, I couldn’t do it.  Suddenly it shows a blank view and not even the Shared.view was shown.

### CAUSE:
I guess this is because the new way to save things as Bytes through Lamdera. But I am not sure.

### SOLUTION:
I had to change the body from List (Html Msg) to String. And also, do the markdown processing in the view function. And it worked ok.

### OBSERVATION:
I liked the previous way better. Because, when the markdown processing was done in the pre-rendering step, the view functions became lighter (with less work done on the client). I’m not sure but, also the markdown processing code could be (and I don’t know if this is done already) tree shaken – gone from code elimination, from the clients downloaded javascript assets (becoming smaller).

It's ok if it has to be this way, given the bigger picture you have. Just I would like to confirm if this is intentional or something else is going on that I'm not getting.

Regards,

**Comment by dillonkearns** [comment]
That's correct that Lamdera encoding is the reason you can't send HTML over the wire. Mario is working on something in the Lamdera executable that will give an error message pointing to the data type that is causing the error to give better feedback, so that's already in progress.

> I liked the previous way better. Because, when the markdown processing was done in the pre-rendering step, the view functions became lighter (with less work done on the client). I’m not sure but, also the markdown processing code could be (and I don’t know if this is done already) tree shaken – gone from code elimination, from the clients downloaded javascript assets (becoming smaller).

Actually, it's the opposite. It was not possible to do dead code elimination on the code for `DataSource`s in 2.0, and with 3.0 the DataSource is dead code eliminated, so that's one of the huge wins that comes from using Lamdera Wire for the encoding (instead of OptimizedDecoder). Before, it was possible to use `distill` to reduce down the JSON data that was sent, but it wasn't possible to dead code eliminate the code itself from the client bundle, and it was very difficult to use distill to reduce the data. With the Lamdera wire encoding, everything is distilled automatically, which means there is no more redundant computation on the build and then again on the client hydration. And this happens in all cases, not only when you manually define the distill step.

I wish that HTML was serializable in Lamdera, I've been thinking about ways to make that nice. But what I've been doing with my markdown is having the DataSource be the parsed markdown, and then render that markdown in the view.

For example, that's what I'm doing for the elm-pages docs site here:

https://github.com/dillonkearns/elm-pages/blob/e6fb1047ecb1933ce3304a23b9b73246d47a097b/examples/docs/app/Route/Blog/Slug_.elm#L236-L241

https://github.com/dillonkearns/elm-pages/blob/e6fb1047ecb1933ce3304a23b9b73246d47a097b/plugins/MarkdownCodec.elm#L192-L222

**Comment by dillonkearns** [comment]
I'll close this issue since it's being tracked separately. Thanks!

**Comment by rolojf** [comment]
Thanks for closing the loop. I get it.
